- hosts: Centos_Web
  handlers:
  - name: "restart {{ service_name }}"
    service:
      name: "{{ service_name }}"
      state: restarted
  tasks:
  - include_tasks: "{{ ansible_os_family }}-ntpd.yml"

- hosts: all
  handlers:
  - name: "restart {{ service_name }}"
    service:
      name: "{{ service_name }}"
      state: restarted
  tasks:
  - include_tasks: "RedHatOthers-ntpd.yml"

- hosts: Ubuntu_DB
  handlers:
  - name: "restart {{ service_name }}"
    service:
      name: "{{ service_name }}"
      state: restarted
  tasks:
  - include_tasks: "{{ ansible_os_family }}-ntpd.yml"

